### ISSUE TITLE
Collections support

### ISSUE THREAD

**Issue by XhmikosR** [jekyll/jekyll-feed#124]
Say, I have the following config

``` yml
collections:
    posts:
        permalink: /blog/:year/:month/:day/:title/
        output: true
    updates:
        permalink: /:collection/:year/:month/:day/
        output: true
```

Is it possible to generate a separate feed for updates?
