### ISSUE TITLE
Invalid scheme format

### ISSUE THREAD

**Issue by mmistakes** [jekyll/jekyll-feed#191]
Using the latest version of jekyll-feed (0.9.2) the following error occurs:

```
  Liquid Exception: Invalid scheme format: {"feature"=>"so-simple-sample-image-7.jpg", "credit"=>"WeGraphics", "creditlink"=>"http in feed.xml
```

Due to posts` with YAML Front Matter like this:

```yaml
image:
  feature: so-simple-sample-image-1.jpg
  credit: WeGraphics
  creditlink: http://wegraphics.net/downloads/free-ultimate-blurred-background-pack/
```

Looks like anything after version `0.5.1` breaks. I believe something similar happened to `jekyll-seo-tag` before moving the image object to a drop.

Sample repo that exhibits the problem can be found here for testing:

- https://github.com/mmistakes/so-simple-theme

```
clone repo
bundle update
bundle exec jekyll build
```

**Comment by pathawks** [comment]
You will need to [add a `path`](https://github.com/jekyll/jekyll-feed#optional-front-matter) to the URL of the image.

```yaml
image:
  path: http://example.com/so-simple-sample-image-1.jpg
  feature: so-simple-sample-image-1.jpg
  credit: WeGraphics
  creditlink: http://wegraphics.net/downloads/free-ultimate-blurred-background-pack/
```
