### ISSUE TITLE
Change title of feed

### ISSUE THREAD

**Issue by ffes** [jekyll/jekyll-feed#198]
Right now, `{{site.title}}` is used as the title of the feed.
It would be great if I could add this to `_config.yml` and change the title of the feed.

```yaml
feed:
  title: My awesome weblog
  subtitle: I write great articles about awesome stuff
```

`subtitle` obviously overrides `{{site.description}}`

For instance, the [feed on jekyllrb.com](https://jekyllrb.com/feed.xml) could be renamed to "Jekyll News" this way.
