### ISSUE TITLE
Published posts do not appear in feed

### ISSUE THREAD

**Issue by localheinz** [jekyll/jekyll-feed#202]
Not entirely sure what the problem is, but it appears that published posts do not appear in the feed anymore.

See https://github.com/jekyll/jekyll-feed/blob/v0.9.2/lib/jekyll-feed/feed.xml#L34.

I circumvented the problem for now by specifying a front matter default value for `draft`.

```yml
  - scope:
      path: ""
      type: posts
    values:
      draft: false # Otherwise published posts do not appear in feed (see https://github.com/jekyll/jekyll-feed/blob/v0.9.2/lib/jekyll-feed/feed.xml#L34)
```

Will take a look later whether it has something to do with upgrading (https://github.com/jekyll/jekyll/compare/v3.6.2...v3.7.0).
