### ISSUE TITLE
Can the {% feed_meta %} helper tag pull feed dynamically?

### ISSUE THREAD

**Issue by softcomux** [jekyll/jekyll-feed#242]
I was wondering if the `{% feed_meta %}` can pull feeds dynamically, that is, based on the page it's on. In my case, I don't have a "posts" collection but collections by other names

```
feed:
  collections:
    skills:
      path: '/feeds/skills.xml'
    thinklist:
      path: '/feeds/thinklist.xml'
    words:
      path: '/feeds/words.xml'
```

So I expect that when I'm on the "skills" archive the `{% feed_meta %}` helper tag should pull feeds on this page, not the default `/feed.xml` which is blank in my case since I don't have a `_post` collection. And so on for others...

Or if there's a way to make all three feeds show in the head section on my site's tree?
