### ISSUE TITLE
failed to crated multiple feed

### ISSUE THREAD

**Issue by wsdjeg** [jekyll/jekyll-feed#244]
I have added this config to _config.yml

```yml
feed:
    blog:
      path: "/feed.xml"
      categories:
        - blog
    cnblog:
      path: "/cn/feed.xml"
      categories:
        - blog_cn

```

what I hope is to create two feed, 
- `http://127.0.0.1:4000/feed.xml`: for post with categories: blog
- `http://127.0.0.1:4000/cn/feed.xml`: for post with categories: blog_cn

But I get 404, when try to open `http://127.0.0.1:4000/cn/feed.xml`,  

`http://127.0.0.1:4000/feed.xml` works well, but all post included blog_cn are in it.
