### ISSUE TITLE
Better author support

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-feed#28]
Allow defining a site/post author as a simple key value pair (`name: Ben`) or, as an object, e.g.:

```yml
author:
  name: Ben
  uri: "http://ben.balter.com"
  email: ben@example.com
```

In the first case, we'd just set `author.name` to `Ben`, and in both cases, only output the field (which is supported within the atom spec) if present.
