### ISSUE TITLE
Author field returned in raw object

### ISSUE THREAD

**Issue by pingu8007** [jekyll/jekyll-feed#299]
Since Atom feed is extended from XML, an author field should be something human readable. This plugin, however, return an object-like string in this field.
I can't find an example with twitter handle, just a feeling.

## Input

```yaml
# _data/authors.yml
PinGu:
  twitter: pinguotaku
  picture: /images/avatar.png
  url: http://example.org/
```

```yaml
# _config.yml
author: PinGu
```

## Expected output

I don't know which is correct but it should be a text at least.

```xml
<feed>
  <author>
    <name>PinGu</name>
    <url>http://example.org/</url>
  </author>
  <entry>
    <author>
      <name>PinGu</name>
      <url>http://example.org/</url>
    </author>
  </entry>
</feed>
```
or
```xml
<feed>
  <author>
    <name>@pinguotaku</name>
    <url>http://example.org/</url>
  </author>
  <entry>
    <author>
      <name>@pinguotaku</name>
      <url>http://example.org/</url>
    </author>
  </entry>
</feed>
```

## Actual output

```xml
<feed>
  <author>
    <name>PinGu</name> # Not following _data/authors.yml
  </author>
  <entry>
    <author>
      <name>{"twitter"=>"pinguotaku", "picture"=>"/images/avatar.png", "url"=>"http://example.org/"}</name> # object-like string with all value
    </author>
  </entry>
</feed>
```

## Workaround

Add key `name` to author

```yaml
# _data/authors.yml
PinGu:
  name: Pin
  twitter: pinguotaku
  picture: /images/avatar.png
  url: http://example.org/
```

and the result will be
```xml
<feed>
  <author>
    <name>PinGu</name> # Still not following _data/authors.yml
  </author>
  <entry>
    <author>
      <name>Pin</name> # Only name field, others are missing
    </author>
  </entry>
</feed>
```
