### ISSUE TITLE
Feed_meta Tag Doesn't Populate All Feeds

### ISSUE THREAD

**Issue by thewarden** [jekyll/jekyll-feed#334]
When I use {% feed_meta %} I noticed that it only populates my posts collection feed. I have 3 other collections setup and they are never populated. Indeed the feed files are generated within the "/feed/" directory as configured.

Am I missing something? I don't see anything referring to this in the documentation on how to enable it for other collections.

I have the following jekyll-feed configuration in `_config.yml` as follows.

```yml
feed:
    path: /feed/blog.xml
    posts_limit: 50
    collections:
        - adamsdesk
        - mindfulsations
        - sfa
```
