### ISSUE TITLE
Lowercase category names

### ISSUE THREAD

**Issue by bbatsov** [jekyll/jekyll-feed#351]
With the following config:

```
feed:
  path: atom.xml
  categories:
    - Emacs
```

the feed for the category Emacs, ends up being named `feed/Emacs.xml` instead of `feed/emacs.xml`. I took me a while to figure this out as I expected that the feed would named `feed/emacs.xml`, but trying to access it resulted in a 404. As capitalized names are uncommon in URLs, I think it makes sense to just lowercase category names.
