### ISSUE TITLE
Support variables in _config.yml path name and absolute file path

### ISSUE THREAD

**Issue by drscream** [jekyll/jekyll-feed#360]
It would be nice if variables could be used in the `path` value for the `tag` option. For example:

```yml
feed:
  tags:
    path: /tag/:tag/index.xml
```

This should allow the user to generate feeds per tag in the tag folder with the name of the file.
