### ISSUE TITLE
excerpt_only doesn't work

### ISSUE THREAD

**Issue by Jmuccigr** [jekyll/jekyll-feed#413]
In my setup, setting:

```
feed:
  icon: /images/icon.png
  logo: /images/logo.png
  excerpt_only: true
```
doesn't work. The feed still has all the content in it.
