### ISSUE TITLE
Find author by reference

### ISSUE THREAD

**Issue by silvenon** [jekyll/jekyll-feed#62]
On my blog there are two authors. Their properties are defined in the `_config.yml`:

```yml
authors:
  foo:
    name: "Foo"
    email: "foo@domain.com"
    uri: "http://foo.com"
  bar:
    name: "Bar"
    email: "bar@domain.com"
    uri: "http://bar.com"
```

In the post's YAML frontmatter I put:

```yml
title: My Post
author: foo
```

Then later I extract the actual author with `site.authors[post.author]`. I do this so I don't have to write all those details in each post.

Is there a way to make something like this work with jekyll-feed?

**Comment by benbalter** [comment]
> Is there a way to make something like this work with jekyll-feed?

This is not something that's currently supported. Author information must either be universal in the configuration or specific to the post.

**Comment by silvenon** [comment]
Ok. It's not that big of a deal anyway.

**Comment by parkr** [comment]
I certainly wouldn't mind supporting something like this if we decide we think having an authors datafile is the "best practice".

**Comment by silvenon** [comment]
Ok, I'll reopen for a possible discussion. Close if you decide against it :+1:

**Comment by sondr3** [comment]
Please do, it would be great to have some official best practices regarding naming stuff in your `_config.yml` file and so on, because right now it's a bit of a mess :smiley:

**Comment by silvenon** [comment]
This seems reasonable…

`config.yml`:
```yml
authors:
  default:
    name: "Default"
    email: "default@domain.com"
    url: "http://default.com"
  foo:
    name: "Foo"
    email: "foo@domain.com"
    uri: "http://foo.com"
  bar:
    name: "Bar"
    email: "bar@domain.com"
    uri: "http://bar.com"
```

`_posts/my-post.md`:
```yml
title: My Post
# author defaults to site.authors.default
```

`_posts/my-other-post.md`
```yml
title: My Other Post
author: foo
# maps to site.authors.foo
```

But I guess in order for this to make sense, it needs to be a Jekyll feature?
